name: build
on: push
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest
    steps:
      - uses: make setup
      - uses: make start
      # Запускаем линтер
      - run: make lint
      # Запускаем тесты
      - name: run tests # имя шага, помогает отладке, выводится на Github при просмотре сборки
        run: make test # name и run относятся к одной задаче, поэтому дефис ставится только перед name